CREATE TABLE IF NOT EXISTS alarms (
  id INTEGER PRIMARY KEY,
  foreign_id VARCHAR UNIQUE,
  title VARCHAR NOT NULL,
  description VARCHAR,
  "address" VARCHAR,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  "priority" BOOLEAN DEFAULT FALSE,
  notification_type INTEGER,
  created TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alarm_returns (
  id INTEGER PRIMARY KEY,
  alarm_id INTEGER NOT NULL,
  returned_at TIMESTAMP NOT NULL,
  notes VARCHAR,
  CONSTRAINT fk_alarm FOREIGN KEY (alarm_id) REFERENCES alarms (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, "name" VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS "groups" (id INTEGER PRIMARY KEY, "name" VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS vehicles (
  id INTEGER PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  fullname VARCHAR NOT NULL,
  shortname VARCHAR NOT NULL,
  issi CHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS answer_codes (id INTEGER PRIMARY KEY, label VARCHAR NOT NULL);
