openapi: 3.0.1
info:
  version: 4.0.2
  title: DIVERA 24/7 RESTful Webservice
  description: |
    ## Authentifizierung
    Um sich gegenüber der DIVERA 24/7-API zu authentifizieren, gibt es verschiedene Möglichkeiten.
    **WICHTIG: Teilen Sie Ihre Zugangsdaten oder API-Keys mit niemanden, auch nicht mit der DIVERA GmbH. Nutzen Sie für jede Anwendung/Schnittstelle stets unterschiedliche System-Benutzer bzw. API-Keys.**

    ### System-Benutzer
    Für die Nutzung der API, empfehlen wir einen System-Benutzer anzulegen und keinen personenbezogenen Nutzer zu verwenden. Das hat nicht nur den Vorteil, dass die Berechtigungen auf das nötigste eingeschränkt werden können, und Interaktionen eindeutig einem Script oder einer Schnittstelle zugeordnet werden können. Zudem kann ein API-Key direkt in der Web-App abgerufen werden. **Hierzu sind Verwaltungsrechte erforderlich!**

    ### API-Key abrufen
    Ein API-Key (teilweise auch Accesskey genannt) kann über den Endpunkt `/api/v2/auth/login` unter Angabe der Zugangsdaten (Nutzername + Pasiswort) abgerufen werden. In der Server-Antwort ist unter `data.user.access_token` der API-Key enthalten.

    ### API-Key übermitteln
    Bei Aufruf jedes API-Endpunkts (Ausnahme: Login) muss dann der API-Key zur Authentifizierung mit angegeben werden.
    #### Query-Parameter (`accesskey`)
    Als einfachste Möglichkeit kann der API-Key der URL als Query-Parameter angegeben werden, bspw. `/api/pull?accesskey=mein-geheimer-api-key`.
    #### Body-Parameter (`accesskey`)
    Für Endpunkte die `POST`/`PUT`/`DELETE` nutzen, kann als Body-Parameter ebenfalls der API-Key angegegeben werden, bspw.
    ```json
    {
        "accesskey": "mein-geheimer-api-key",
        [... restlicher Payload ...]
    }
    ```
    #### Header `Authorization`
    Als `Bearer`-Token kann ein Json-Web-Token angegeben werden. Die Unterstützung der Übermittlung des regulären API-Keys als `Authorization` wird künftig nachgeliefert.

    ### Json-Web-Token abrufen
    Über `/api/v2/auth/login?jwt=true` kann unter Angabe von Benutzername + Passwort oder alternativ unter Angabe eines API-Keys kann über `/api/v2/auth/jwt?accesskey=mein-geheimer-api-key` ein Json-Web-Token erhalten werden. Dieser ist zeitlich begrenzt und muss regelmäßig über einen API-Key erneuert werden.
    Die Ablaufdaten sind aus dem JWT-Header auslesbar.

    Anschließend kann ein JWT als Header `Authorization: Bearer mein-geheimer-jwt` gesendet werden.

servers:
  - url: https://app.divera247.com
tags:
  - name: Login
    description: Authentifizierung gegenüber der API
paths:
  /api/v2/auth/login:
    post:
      tags:
        - Login
      summary: API-Key (Accesskey) abrufen
      description: Abruf eines API-Keys (optional zzgl. JWT) über die Angabe von Benutzername + Passwort. Der API-Key wird in der Server-Antwort unter `data.user.access_token` zurückgegeben.
      parameters:
        - name: jwt
          in: query
          description: Optional zusätzlich Json-Web-Token abfragen
          type: boolean
          example: true
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                Login:
                  type: object
                  required:
                    - username
                    - password
                    - jwt
                  properties:
                    username:
                      description: E-Mail-Adresse
                      type: string
                      example: heinz.meinz@musterstadt.de
                    password:
                      description: Passwort
                      type: string

      responses:
        200:
          description: Rückgabewert bei erfolgreicher Anmeldung wie auch bei Fehlern (errors beachten)
          content:
            'application/json':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: TRUE
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          access_token:
                            type: string
                            description: API-Accesskey für alle weiteren Requests
                          autologin:
                            type: boolean
                            description: Definiert, ob der automatische Login im Browser erlaubt ist. Dient primär dem Monitor-Benutzer einer Einheit.
                          auth_key:
                            type: string
                            description: Schlüssel für den Autologin eines Monitor-Benutzers.
                          default_user_cluster_relation:
                            type: integer
                            description: UserClusterRelation (kurz 'UCR') steht für die Verknüpfung eines Benutzers mit einer Einheit. Über default_user_cluster_relation wird bestimmt, welche UCR nach dem Login initialisiert wird.
                      ucr:
                        type: object
                        description: Enthält alle Verknüpfungen eines Anwenders zu seinen Einheiten.
                      errors:
                        type: object
                        properties:
                          username:
                            type: string
                          password:
                            type: string

  /api/v2/auth/jwt:
    get:
      tags:
        - Login
      summary: JSON-Web-Token abrufen
      description: |
        Abruf eines JSON-Web-Tokens (JWT) zur Verwendung als Bearer-Token im Authorization Header (`Authorization: Bearer mein-geheimer-jwt`)

        Die Gültigkeit ist beschränkt und im Header des Tokens enthalten. Wenn der JWT abgelaufen ist, gibt die API den Fehler-Code 401 zurück.
      responses:
        200:
          content:
            'application/json':
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: TRUE
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
        403:
          description: Accesskey fehlt oder ungültig
          content: {}
      security:
        - Personal-API-Accesskey: []
components:
  securitySchemes:
    Personal-API-Accesskey:
      type: apiKey
      name: accesskey
      in: query
